name: GitHubTickets
version: ${project.version}
main: com.tallcraft.githubtickets.GithubTickets
api-version: 1.13
authors: [Tallcraft]
description: Ticket System based on GitHub Issues
commands:
  ticket:
    description: Create and manage tickets
