name: GitHubTickets
version: ${project.version}
main: com.tallcraft.githubtickets.GithubTickets
api-version: 1.13
authors: [Tallcraft]
description: Ticket system interfacing with GitHubController
commands:
  ticket:
    description: Create and manage tickets
    usage: /ticket
